title: Articulos del Curso 110?
description: "Para cumplir con la materia, yeii"
author:
  name: "nueva-zelandia-colegio"
  email: "no-hay"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "algunas personas de 11"
year : "2022"
